### ISSUE TITLE
Connecting window can't move and opens above kde authenticator

### ISSUE THREAD

**Issue by foxtrotdragon** [calexandru2018/protonvpn-linux-gui#103]
On plasma when you connect to a server, the connecting window will pop up, you can't move the windows and it stays on the foreground covering the box to enter password on plasma, its not breaking but you need to move the plasma box over to begin typing or click on the small portion of text box available, 

which is highly annoying

**Comment by calexandru2018** [comment]
Hi @foxtrotdragon 

I guess you're referring to #88 ? If so, please close this issue as it is a duplicate.

**Comment by foxtrotdragon** [comment]
I suppose I am I didnt check to see the authenitcation was as I just wanted to move it out of the way
