### ISSUE TITLE
Could not load necessary resources

### ISSUE THREAD

**Issue by mbfakourii** [calexandru2018/protonvpn-linux-gui#104]
hi i can not run gui Proton VPN has error 

```
Could not load necessary resources, there might be connectivity issues
```
i cheng api_domain in utils.py from https://api.protonvpn.ch to https://api.protonmail.ch but not work

**Comment by calexandru2018** [comment]
Hi @flashiran1 , could you please provide more information by filling in the template ? Thank you.

**Comment by mbfakourii** [comment]
- OS: Ubuntu
 - Browser chrome
 - Version 85.0.4183.102


@calexandru2018 What information do you need exactly??
