### ISSUE TITLE
Can't install gir1.2-appindicator3

### ISSUE THREAD

**Issue by roadrunner56** [calexandru2018/protonvpn-linux-gui#108]
**Describe the bug**
In the `README` file, it states that one of the dependencies for the system tray in Debian-based systems is `gir1.2-appindicator3`. However, I was unable to install this dependency. Instead, I got an error message stating that it was unable to locate `gir1.2-appindicator3`. I am unsure if this is an error in the documentation, something wrong with the dependency itself, or simply something on my end.

**To Reproduce**
1. Copy and paste the command given to install systray dependencies in Debian-based systems. This is as follows: `sudo apt install -y gir1.2-appindicator3 libnotify-bin`
2. Enter superuser password.
3. The system will return a message saying that it is unable to locate the package `gir1.2-appindicator3`

**Expected behavior**
I expected `apt` to recognize the program and install it. 

**Screenshots**
![Can't install](https://user-images.githubusercontent.com/65418682/97761698-fd94c200-1acb-11eb-83a0-842b83fe8ac2.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Version 2.1.1

**Additional context**
`libnotify-bin`, another systray dependency, was installed without any issues.
Apologies if this is something on my end.

**Comment by calexandru2018** [comment]
Hey @roadrunner56 

This is something that has been mentioned in #89 . As I've understood it's certain ubuntu versions don't recognize it.

This will be fixed in the near future, as the current CLI clients are being rewriten, with improved security features.

**Comment by roadrunner56** [comment]
My bad, I'll close the issue then.
