### ISSUE TITLE
Can't install on Linux Mint 19.3

### ISSUE THREAD

**Issue by Marek-Moehling** [calexandru2018/protonvpn-linux-gui#114]
**Describe the bug**

Error msg:
```
~$ protonvpn-gui
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn-gui", line 5, in <module>
    from linux_gui.protonvpn_gui import init
  File "/usr/local/lib/python3.6/dist-packages/linux_gui/protonvpn_gui.py", line 6, in <module>
    from protonvpn_cli.constants import CONFIG_FILE, CONFIG_DIR #noqa
ImportError: cannot import name 'CONFIG_FILE'
```

**To Reproduce**
1. sudo pip3 install protonvpn-gui
2. protonvpn-gui

**Expected behavior**
protonvpn-gui starts with a gui.

**Desktop:**
 - OS: Linux Mint 19.3 
 - Browser: Firefox
 - Version: 83.0
 
 **Other**
 
```
/usr/local/lib/python3.6/dist-packages/linux_gui/protonvpn_gui.py

Lines 6 and 7:
  from protonvpn_cli.constants import CONFIG_FILE, CONFIG_DIR #noqa
  from protonvpn_cli.utils import check_root #noqa
```

 Seems like files are not named as expected:
```
/usr/local/lib/python3.6/dist-packages/linux_gui
/usr/local/lib/python3.6/dist-packages/linux_gui/presenters
/usr/local/lib/python3.6/dist-packages/linux_gui/resources
/usr/local/lib/python3.6/dist-packages/linux_gui/services
/usr/local/lib/python3.6/dist-packages/linux_gui/views
/usr/local/lib/python3.6/dist-packages/linux_gui/constants.py
/usr/local/lib/python3.6/dist-packages/linux_gui/gui_logger.py
/usr/local/lib/python3.6/dist-packages/linux_gui/indicator.py
/usr/local/lib/python3.6/dist-packages/linux_gui/__init__.py
/usr/local/lib/python3.6/dist-packages/linux_gui/protonvpn_gui.py
/usr/local/lib/python3.6/dist-packages/linux_gui/utils.py
```

**Comment by calexandru2018** [comment]
Hey @Marek-Moehling 

Can you use the CLI ? If so, please paste the output of protonvpn-cli --version or protonvpn --version.

**Comment by Marek-Moehling** [comment]
~$ protonvpn-cli --version
ProtonVPN CLI v3.0.0 (protonvpn-nm-lib v0.1.0; proton-client v0.1.0)

Works fine.

**Comment by calexandru2018** [comment]
The current GUI does not work with the official version as they are different implementations. It is though being currently rewritten.

**Comment by Finoway** [comment]
> The current GUI does not work with the official version as they are different implementations. It is though being currently rewritten.

You are going to make a detection of the version of protonvpn to prevent directly that the version is not the good one ? Say which one should be used?

**Comment by calexandru2018** [comment]
Hey @Finoway

I've previously written that the current client is being rewriten. So until it's complete, no further updates are going to be released.
