### ISSUE TITLE
Choice "sudo", "pkexec" and other...

### ISSUE THREAD

**Issue by Finoway** [calexandru2018/protonvpn-linux-gui#115]
**Is your feature request related to a problem? Please describe.**
I have to launch the GUI with a terminal because it runs sudo, which is impractical. 

**Describe the solution you'd like**
Being able to choose if you want to use "sudo", "pkexec" or other for the moment of connecting to protonvpn.

**Additional context**
I thought at the beginning that the GUI would not work because when I click on "Quick Connect" nothing happens from the window "connection to the server" because in fact it asks for permission in the terminal but since I launch it with the shortcut created by the [AUR package](https://aur.archlinux.org/packages/protonvpn-linux-gui) . I don't see sudo. I don't know if it can be useful but I'm on manjaro kde with the kernel "5.9.11-3-MANJARO".

**Comment by Finoway** [comment]
I just saw that it's already there, it would be nice to activate it from the default.

**Comment by calexandru2018** [comment]
This will not be necessary after the client had been completely rewriten.
