### ISSUE TITLE
ProtonVPN UI based on CLI commands 

### ISSUE THREAD

**Issue by shawndfernandes** [calexandru2018/protonvpn-linux-gui#120]
https://github.com/shawndfernandes/ProtonVPN-UI

ProtonVPN UI for Ubuntu 20

A convienient UI tool to trigger protonVPN cli commands via UI.

Tested on Ubuntu 20, built with gtkmm3.0.

Instructions:

Run ./main from terminal, or copy main to /usr/local/bin folder.

Pre requisites : ProtonVPN CLI on Unix

https://protonvpn.com/blog/linux-vpn-cli-beta/

Additional Links :

https://protonvpn.com/support/linux-vpn-tool/

https://github.com/ProtonVPN/linux-cli
![VPN-SNap](https://user-images.githubusercontent.com/16843666/107719537-0d609c80-6c9e-11eb-8ac5-c9e5337577ab.png)

**Comment by calexandru2018** [comment]
Hey @shawndfernandes 

Thank you for your contribution. Even though we appreciate you taking the time and effort in creating something own and sharing it, it does not help by creating three additional issues and answering them yourself with a link to your project. Instead, you could share on social media platforms such as reddit, twitter and/or mastodon. Please close this and the previous two issues, as it has already been previously answered that the current GUI does not work with the official CLI.
