### ISSUE TITLE
Every country below Norway just disappeared,

### ISSUE THREAD

**Issue by tsaewong** [calexandru2018/protonvpn-linux-gui#121]
**Describe the bug**
Some time in the last hour i have lost the ability to connect to any countries above the letter N. no changes were made, no updates.

**To Reproduce**
1. Open
2. Scroll down country list

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: NA

**Additional context**
None.

**Comment by tsaewong** [comment]
i can force it in terminal, so not a deal killer, hopefully an update someday fixes this because i don't seem to be the only one.

**Comment by calexandru2018** [comment]
Hey @tsaewong 

This issue already been mentioned some times. 
I've also mentioned that this gui will not receive any further updates, as the official one is currently under development.

This GUI is based on the community version, which suffers from certain problems/limitations.
